// Flutter 3.24 / Dart 3.5
class PetDiaryEntry {
  final String id;
  final DateTime date;
  final String content;
  final String mood;
  final List<String> tags;
  final bool autoGenerated;

  PetDiaryEntry({
    String? id,
    DateTime? date,
    required this.content,
    this.mood = '📝',
    List<String>? tags,
    this.autoGenerated = false,
  })  : id = id ?? DateTime.now().microsecondsSinceEpoch.toString(),
        date = date ?? DateTime.now(),
        tags = List.from(tags ?? []);

  Map<String, dynamic> toJson() => {
    'id': id,
    'date': date.toIso8601String(),
    'content': content,
    'mood': mood,
    'tags': tags,
    'autoGenerated': autoGenerated,
  };

  factory PetDiaryEntry.fromJson(Map<String, dynamic> json) {
    return PetDiaryEntry(
      id: json['id'] as String?,
      date: json['date'] != null
          ? DateTime.tryParse(json['date'] as String)
          : null,
      content: json['content'] as String? ?? '',
      mood: json['mood'] as String? ?? '📝',
      tags: (json['tags'] as List<dynamic>?)
          ?.map((e) => e.toString()).toList() ?? [],
      autoGenerated: json['autoGenerated'] == true,
    );
  }
}
