// Flutter 3.24 / Dart 3.5
import 'package:flutter_test/flutter_test.dart';
import 'package:deepseek_chat/models/pet_diary.dart';

void main() {
  group('PetDiaryEntry', () {
    test('toJson/fromJson 往返', () {
      final now = DateTime.now();
      final entry = PetDiaryEntry(
        id: 'diary-1',
        date: now,
        content: '今天糯糯认识了新朋友~',
        mood: '😊',
        tags: ['初识', '互动'],
        autoGenerated: true,
      );
      final json = entry.toJson();
      final restored = PetDiaryEntry.fromJson(json);
      expect(restored.id, 'diary-1');
      expect(restored.content, '今天糯糯认识了新朋友~');
      expect(restored.mood, '😊');
      expect(restored.tags, ['初识', '互动']);
      expect(restored.autoGenerated, true);
    });

    test('默认值', () {
      final entry = PetDiaryEntry(content: '测试日记');
      expect(entry.id, isNotEmpty);
      expect(entry.mood, '📝');
      expect(entry.autoGenerated, false);
      expect(entry.tags, isEmpty);
    });

    test('fromJson 缺字段默认值', () {
      final entry = PetDiaryEntry.fromJson({'content': '仅有内容'});
      expect(entry.content, '仅有内容');
      expect(entry.mood, '📝');
    });
  });
}
